// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System.Collections.Generic;

namespace PrlyGrp.CountryCatalog.ApplicationCore.Entities
{
    public partial class Country : DbBaseEntity
    {
        public Country()
        {
            StateProvince = new HashSet<StateProvince>();
        }

        public string Name { get; set; }
        public string ShortName { get; set; }
        public string Code { get; set; }

        public virtual ICollection<StateProvince> StateProvince { get; set; }
    }
}