// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PrlyGrp.CountryCatalog.ApplicationCore.Entities
{
    public partial class EavAttribute : DbBaseEntity
    {
        public EavAttribute()
        {
            EavValue = new HashSet<EavValue>();
        }

        public string Name { get; set; }
        public string ShortName { get; set; }
        public string Label { get; set; }
        public string DataType { get; set; }
        public string DefaultValue { get; set; }
        public bool IsRequired { get; set; }
        public int DisplayOrder { get; set; }
        public int EavEntityId { get; set; }
        public string EavEntityShortName { get; set; }

        public virtual EavEntity EavEntity { get; set; }
        public virtual ICollection<EavValue> EavValue { get; set; }
    }
}