// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PrlyGrp.CountryCatalog.ApplicationCore.Entities
{
    public partial class EavValue : DbBaseEntity
    {
        public int EntityId { get; set; }
        public int EavEntityId { get; set; }
        public string EavEntityShortName { get; set; }
        public int EavAttributeId { get; set; }
        public string EavAttributeShortName { get; set; }
        public string Value { get; set; }

        public virtual EavAttribute EavAttribute { get; set; }
        public virtual EavEntity EavEntity { get; set; }
    }
}