// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PrlyGrp.CountryCatalog.ApplicationCore.Entities
{
    public partial class StateProvince : DbBaseEntity
    {
        public string Name { get; set; }
        public string ShortName { get; set; }
        public string Code { get; set; }
        public int CountryId { get; set; }
        public string CountryCode { get; set; }

        public virtual Country Country { get; set; }
    }
}